# Generated by Django 3.2.2 on 2021-05-17 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id_tipo_cargo', models.FloatField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'cargo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.FloatField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.FloatField(blank=True, null=True)),
                ('celular', models.FloatField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('country_id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('country_name', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'countries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('department_id', models.IntegerField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'departments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.FloatField()),
                ('id_vehiculo', models.FloatField()),
            ],
            options={
                'db_table': 'detalle_cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleInforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_info_vehiculo', models.FloatField()),
                ('id_presupuesto', models.FloatField()),
            ],
            options={
                'db_table': 'detalle_informe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleOp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_info_vehiculo', models.FloatField()),
                ('id_orden_pedido', models.FloatField()),
            ],
            options={
                'db_table': 'detalle_op',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_orden_pedido', models.FloatField()),
                ('id_pago', models.FloatField()),
            ],
            options={
                'db_table': 'detalle_orden',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id_detalle_pedido', models.FloatField(primary_key=True, serialize=False)),
                ('cod_producto', models.FloatField()),
                ('cantidad', models.FloatField()),
                ('precio', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'detalle_pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_reserva', models.FloatField()),
                ('id_orden_trabajo', models.FloatField()),
            ],
            options={
                'db_table': 'detalle_reserva',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.FloatField(primary_key=True, serialize=False)),
                ('id_cargo', models.FloatField()),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('contacto', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'empleado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=25, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('hire_date', models.DateField()),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('commission_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True)),
            ],
            options={
                'db_table': 'employees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoVehiculo',
            fields=[
                ('id_estado', models.FloatField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'estado_vehiculo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InfoAuto',
            fields=[
                ('id_informe', models.FloatField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'info_auto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('job_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=35)),
                ('min_salary', models.IntegerField(blank=True, null=True)),
                ('max_salary', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jobs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('location_id', models.IntegerField(primary_key=True, serialize=False)),
                ('street_address', models.CharField(blank=True, max_length=40, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=12, null=True)),
                ('city', models.CharField(max_length=30)),
                ('state_province', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'locations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Op',
            fields=[
                ('id_pedido', models.FloatField(primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateField()),
                ('hora_pedido', models.CharField(max_length=10)),
                ('fecha_entrega', models.DateField()),
            ],
            options={
                'db_table': 'op',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ot',
            fields=[
                ('id_orden', models.FloatField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('servicio', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'ot',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.FloatField(primary_key=True, serialize=False)),
                ('fecha_emision', models.DateField()),
                ('tipo_recibo', models.CharField(max_length=10)),
                ('monto', models.FloatField()),
                ('iva', models.FloatField()),
            ],
            options={
                'db_table': 'pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id_presupuesto', models.FloatField(primary_key=True, serialize=False)),
                ('precio', models.FloatField(blank=True, null=True)),
                ('iva', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'presupuesto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.FloatField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('pro_cod_producto', models.FloatField()),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.FloatField(primary_key=True, serialize=False)),
                ('contacto', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('rubro', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'proveedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('region_id', models.FloatField(primary_key=True, serialize=False)),
                ('region_name', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'regions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id_reserva', models.FloatField(primary_key=True, serialize=False)),
                ('servicio', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha', models.DateField()),
                ('hora', models.CharField(max_length=10)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'reservas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id_servicio', models.FloatField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('monto', models.FloatField()),
                ('tiempo_serv', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'tipo_servicio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id_vehiculo', models.FloatField(primary_key=True, serialize=False)),
                ('matricula', models.CharField(max_length=10)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('num_chasis', models.CharField(blank=True, max_length=50, null=True)),
                ('year', models.FloatField(blank=True, null=True)),
                ('ultimo_servicio', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vehiculo',
                'managed': False,
            },
        ),
    ]
